# Generated by Django 2.0.1 on 2018-01-23 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilono_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlecture',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
