# Generated by Django 2.0.1 on 2018-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babilono_app', '0003_remove_student_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
